
s = set() 
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)
enter = input("enter number:   ")
s.add(enter)


print(s)